var names = [
    "Carman Wardlow",
    "France Sirois",
    "Drew Presti",
    "Sharri Strobel",
    "Margherita Dagenhart",
    "Cristin Haddock",
    "Laticia Barreras",
    "Lecia Saylor",
    "Vernice Turman",
    "Darius Jepson",
    "Sam Dodson",
    "Ralph Beaufort",
    "Bertie Fulmer",
    "Nickie Strayer",
    "Delinda Vitti",
    "Karrie Kerby",
    "Zita Sweeten",
    "Mabel Plunkett",
    "Micaela Vautour",
    "Elroy Kentner",
    "Thersa Wilkerson",
    "Jeanie Lustig",
    "Kyung Applewhite",
    "Brittni Bornstein",
    "Despina Biehl",
    "Minh Slater",
    "Shelia Lagace",
    "Sherilyn Gerow",
    "Gladys Weissman",
    "Corie Goodner",
    "Bula Rotella",
    "Antoine Oren",
    "Lourie Kissell",
    "Marina Ned",
    "Edra Mawson",
    "Lai Roeser",
    "Wally Winegar",
    "Lory Haddox",
    "Birgit Saltz",
    "Bruno Zaragosa",
    "Cherryl Camarena"
]

/* 
    TODO: Write a function thats takes the user's name and appends a secret name
          to the DOM.
*/